[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
  "cd portal_wps_backend",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "cd portal_wps_backend && python3 src/main.py"
